OldPanda/Open-the-F-king-URL-Right-Now

userscript.js

refactor: update weibo redirect pattern for new t.cn page

---

userscript.js

第一次用GitHub拉取请求，边Google边弄的，希望没有问题~感谢让我尝试~_(:з)∠)_

添加QQ文档和P站跳转~

---

userscript.js

增加对360doc.cn、百度贴吧、Zaker、天眼查的支持 & 修复bug

---

userscript.js

掘金文章页面中的链接跳转的时候也会有一个中间页，增加了对这个页面的处理

增加掘金网站(juejin.cn)的支持

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/44

Add afdian

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/47

Add QQ email

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/46

Add logonews

---

userscript.js

添加优设UISDC支持

---

userscript.js

添加 Gitee 支持
Update version to 0.16.2
TODO: 跳转目标链接后回退到 Gitee，URL 的 Hash 会被重复添加

添加 Gitee 支持

---

userscript.js

解决微博部分链接无法跳转的问题 并添加酷安、巴哈姆特的支持

---

userscript.js

增加对curseforge，书签地球，企查查的支持

---

userscript.js

To address the issues reported by
* https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/78
* https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/64
and refactored the code structure btw.

Fix image/video display on wechat

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/71

Fix redirect link of wechat

---

userscript.js

Per discussion at the [thread](https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now/discussions/145099)

Update cdn source of jquery

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/78#issuecomment-1373308228

Fix wechat

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/78#issuecomment-1374368924

Exclude wechat edit console

---

userscript.js

测试链接：[https://tieba.baidu.com/mo/q/checkurl?url=https%3A%2F%2Fgithub.com%2FOldPanda%2FOpen-the-F-king-URL-Right-Now](https://tieba.baidu.com/mo/q/checkurl?url=https%3A%2F%2Fgithub.com%2FOldPanda%2FOpen-the-F-king-URL-Right-Now)

添加手机版百度贴吧支持

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/89
and bump version to 1.3.0

Add telegram

---

userscript.js

Sample link: https://www.linkedin.com/safety/go?url=https%3A%2F%2Fwww.create.xyz%2F&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-NDhkNTFkZmQtNmU3My00ZGQ3LTgzYjMtOTg5MTAyMGQ5NmNmXzAxMw%3D%3D

Add support on linkedin redirection page

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/93

Don't edit anything inside a code block of a wechat post

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/95

Fix url redirection from qq page

---

userscript.js

https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/97

Support redirecting from shimo doc

---

userscript.js

有些链接，例如掘金的外链，它做了编码的操作，所以在处理中进行解码

对要跳转的url进行解码

---

userscript.js

Issue: https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/105

Add nodeseek

---

userscript.js

close https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/95

Fix qq ursl redirection

---

userscript.js

测试连接
https://www.baike.com/redirect_link?url=www.baidu.com
https://www.youtube.com/redirect?q=https://www.baidu.com

添加抖音百科和Youtube

---

userscript.js

测试链接：
[https://hd.nowcoder.com/link.html?target=https://github.com/OldPanda/Open-the-F-king-URL-Right-Now](https://hd.nowcoder.com/link.html?target=https://github.com/OldPanda/Open-the-F-king-URL-Right-Now)

add nowcoder

---

userscript.js

Resolves https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/120

Support anime subtitle club

---

userscript.js

Resolves https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/121

Support blzxteam

---

userscript.js

Resolves https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/122

Support luogu

---

userscript.js

Resolves https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/127

Support another shimo outlink url

---

userscript.js

fix(afdian): support new domain for afdian

---

userscript.js

Update jquery cdn source

---

userscript.js

Resolves https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/117

Support migrated wechat account

---

userscript.js

MCBBS已凉,详情: https://mcbbs.rip/

Remove MCBBS

---

userscript.js

support txc

---

userscript.js

add support latexstudio
https://ask.latexstudio.net/go/index?url=https%3A%2F%2Fgithub.com%2Fliuxinyu95%2FAlgoXY

feat: add latexstudio

---

userscript.js

- mczwlt
- techlife
- gitcode
注：这些是基于 1.11.0 版本修改的，可能有些特性已经过时（今天才发现有 gh 仓库，补充一些一年来仍未支持的网站）

support more

---

userscript.js

Example：https://unsafelink.com/https://github.com/chynggi/BAModManager_Python
unsafelink.com是arca.live的外链中间页

feat: support unsafelink

---

userscript.js

eg: https://api.himcbbs.com/refer/?url=https%3A%2F%2Fforum.gamer.com.tw%2FC.php%3Fbsn%3D18673%26snA%3D193576%26tnum%3D1

feat: support himcbbs

---

userscript.js

eg: https://forum.mczwlt.net/outgoing?url=https%3A%2F%2Fspace.bilibili.com%2F3546843661207979

feat: support mczwlt forum
